-- Create database
CREATE DATABASE HomeServiceDB;

-- Users Table
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) UNIQUE NULL,
    Mobile NVARCHAR(50) UNIQUE NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    Role NVARCHAR(50) NOT NULL, -- customer | provider | admin
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

-- Customers Table
CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Birthdate DATE NULL,
    Gender NVARCHAR(50) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

-- Providers Table (Updated with Credits)
CREATE TABLE Providers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Bio NVARCHAR(1000) NULL,
    ExperienceYears INT NULL,
    Gender NVARCHAR(50) NULL,
    Age INT NULL,
    Birthdate DATE NULL,
    AadharNo NVARCHAR(50) NULL,
    AadharFormat NVARCHAR(10) NULL,
    PanNo NVARCHAR(50) NULL,
    PanFormat NVARCHAR(10) NULL,
    VerificationStatus NVARCHAR(50) DEFAULT 'Pending',
    Credits INT DEFAULT 0 NOT NULL, -- NEW: Wallet Balance
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

-- ProviderServices Table
CREATE TABLE ProviderServices (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProviderId UNIQUEIDENTIFIER NOT NULL,
    ServiceId UNIQUEIDENTIFIER NOT NULL,
    CustomPrice DECIMAL(18,2) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id),
    FOREIGN KEY (ServiceId) REFERENCES Services(Id),
    CONSTRAINT UK_Provider_Service UNIQUE(ProviderId, ServiceId)
);

-- Addresses Table
CREATE TABLE Addresses (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Label NVARCHAR(100),
    Line1 NVARCHAR(400),
    Line2 NVARCHAR(400),
    City NVARCHAR(200),
    State NVARCHAR(200),
    Pincode NVARCHAR(50),
    Latitude DECIMAL(9,6) NULL,
    Longitude DECIMAL(9,6) NULL,
    GeoLocation AS (CASE WHEN Latitude IS NOT NULL AND Longitude IS NOT NULL 
                         THEN geography::Point(Latitude, Longitude, 4326) 
                         ELSE NULL END) PERSISTED,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE SPATIAL INDEX [IX_Addresses_GeoLocation] ON Addresses(GeoLocation);

-- Service Categories Table
CREATE TABLE ServiceCategories (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

-- Services Table
CREATE TABLE Services (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(300) NOT NULL,
    Description NVARCHAR(1000),
    CategoryId UNIQUEIDENTIFIER,
    BasePrice DECIMAL(18,2) DEFAULT 0,
    Duration INT NULL, 
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (CategoryId) REFERENCES ServiceCategories(Id)
);

-- Bookings Table
CREATE TABLE Bookings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProviderId UNIQUEIDENTIFIER NULL,  
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    ScheduledAt DATETIME2 NULL,
    AddressId UNIQUEIDENTIFIER NOT NULL,
    Price DECIMAL(18,2) DEFAULT 0,  
    Status NVARCHAR(50) DEFAULT 'pending', 
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id),
    FOREIGN KEY (CustomerId) REFERENCES Users(Id),
    FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);

-- BookingServices Table
CREATE TABLE BookingServices (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BookingId UNIQUEIDENTIFIER NOT NULL,
    ServiceId UNIQUEIDENTIFIER NOT NULL,
    Price DECIMAL(18,2) NOT NULL, 
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    FOREIGN KEY (BookingId) REFERENCES Bookings(Id),
    FOREIGN KEY (ServiceId) REFERENCES Services(Id)
);

-- Payments Table
CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BookingId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    ProviderId UNIQUEIDENTIFIER NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    Status NVARCHAR(50) NOT NULL, 
    PaymentProvider NVARCHAR(200) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (BookingId) REFERENCES Bookings(Id),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id),
    FOREIGN KEY (CustomerId) REFERENCES Users(Id)
);

-- Reviews Table
CREATE TABLE Reviews (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BookingId UNIQUEIDENTIFIER NOT NULL,
    ServiceId UNIQUEIDENTIFIER NOT NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    ProviderId UNIQUEIDENTIFIER NOT NULL,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comment NVARCHAR(2000),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (BookingId) REFERENCES Bookings(Id),
    FOREIGN KEY (ServiceId) REFERENCES Services(Id),
    FOREIGN KEY (CustomerId) REFERENCES Users(Id),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id)
);

-- Notifications Table
CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200),
    Message NVARCHAR(1000),
    IsRead BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

-- Payout Requests Table
CREATE TABLE PayoutRequests (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProviderId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'pending', 
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id)
);

-- Provider Earnings Table
CREATE TABLE ProviderEarnings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProviderId UNIQUEIDENTIFIER NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Type NVARCHAR(100) NOT NULL, 
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id),
    FOREIGN KEY (BookingId) REFERENCES Bookings(Id)
);

-- Admin Logs Table
CREATE TABLE AdminLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AdminId UNIQUEIDENTIFIER NOT NULL,
    Action NVARCHAR(1000) NOT NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (AdminId) REFERENCES Users(Id)
);

-- Media Files Table
CREATE TABLE MediaFiles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    EntityId UNIQUEIDENTIFIER NOT NULL,    
    EntityType NVARCHAR(50) NOT NULL,      
    MediaType NVARCHAR(50) NULL,           
    ImageData VARBINARY(MAX) NOT NULL,     
    Format NVARCHAR(10) NULL,              
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- NEW: Credit Transactions Table
CREATE TABLE CreditTransactions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProviderId UNIQUEIDENTIFIER NOT NULL,
    Amount INT NOT NULL, 
    Type NVARCHAR(50) NOT NULL, -- 'TOPUP', 'JOB_FEE', 'REFUND'
    
    -- CHANGED FROM UNIQUEIDENTIFIER TO NVARCHAR TO SUPPORT STRIPE/RAZORPAY IDs
    ReferenceId NVARCHAR(200) NULL, 
    
    Description NVARCHAR(200) NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (ProviderId) REFERENCES Providers(Id)
);

ALTER TABLE CreditTransactions
ALTER COLUMN ReferenceId NVARCHAR(200);